-- 코드를 입력하세요
SELECT 
  II.INGREDIENT_TYPE, 
  SUM(H.TOTAL_ORDER) AS TOTAL_ORDER
FROM 
  FIRST_HALF H
JOIN 
  ICECREAM_INFO II 
ON 
  H.FLAVOR = II.FLAVOR
GROUP BY 
  II.INGREDIENT_TYPE
ORDER BY 
  TOTAL_ORDER ASC;